version: '3'
services:
  nodejs:
    build: ./nodejs
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:2.0
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=cielnewton
      - DOCKER_INFLUXDB_INIT_BUCKET=ws2024
      - DOCKER_INFLUXDB_INIT_RETENTION=0
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=dQSVkBRNMvJHrjbZFxN_sppfJfC725YiOR2FYX43O5WljhvLN6nnbZIl-5Ass6pGns8Vudfey8bXRS0GlV0mpw==
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb-data:
  grafana-data:
